# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WS16_2012', '0002_auto_20160505_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
