# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WS16_2012', '0003_auto_20160505_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrevision',
            name='task',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='WS16_2012.Task'),
            preserve_default=False,
        ),
    ]
