# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WS16_2012', '0004_taskrevision_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrevision',
            name='project',
        ),
        migrations.AlterField(
            model_name='taskrevision',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
