# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WS16_2012', '0007_auto_20160506_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2016, 5, 7, 11, 15, 0, 582888, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date_finished',
            field=models.DateField(default=datetime.datetime(2016, 5, 7, 11, 15, 9, 434591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
