# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WS16_2012', '0009_auto_20160507_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
